### ISSUE TITLE
Lost custom style in production mode!

### ISSUE THREAD

**Issue by dommi10** [FredrikOseberg/react-chatbot-kit-docs#3]
hi!, i love your product because it easy to integrate but i found an stressing error on production mode.
everything work correctly in dev mode (local machine) but when i deploy on server. all custom css style disappear!
please help!!!!!!!!!!!!!!!!

**Comment by FredrikOseberg** [comment]
Hey. Yeah I'm working on that. For now you can mark your styles with !important. That is a dirty hack, but it should take care of your issue until I can provide a fix.

**Comment by dommi10** [comment]
okay. i build something for my  school expose's with your package and the
result is awesome
Thank you
